"""empty message

Revision ID: 10d6242850d9
Revises: b08f96278b4b
Create Date: 2024-03-22 09:54:50.219344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d6242850d9'
down_revision = 'b08f96278b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_post',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_experience', sa.String(), nullable=False))
        batch_op.drop_column('base_exp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_exp', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('base_experience')

    op.drop_table('user_post')
    # ### end Alembic commands ###
