"""empty message

Revision ID: 9b99331bfa55
Revises: 3c589995b8f0
Create Date: 2024-02-25 00:21:18.464874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b99331bfa55'
down_revision = '3c589995b8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_hp', sa.String(), nullable=False),
    sa.Column('base_attack', sa.String(), nullable=False),
    sa.Column('base_defense', sa.String(), nullable=False),
    sa.Column('sprite_img', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
