"""empty message

Revision ID: b08f96278b4b
Revises: 9c88280e90a4
Create Date: 2024-02-25 11:05:25.929791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08f96278b4b'
down_revision = '9c88280e90a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('base_exp', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('ability', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('sprite_url', sa.String(), nullable=False))
        batch_op.drop_column('sprite_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprite_img', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('sprite_url')
        batch_op.drop_column('ability')
        batch_op.drop_column('base_exp')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
