"""empty message

Revision ID: e84adadbacfa
Revises: 9b99331bfa55
Create Date: 2024-02-25 09:14:07.064400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84adadbacfa'
down_revision = '9b99331bfa55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('base_defense')
        batch_op.drop_column('base_attack')
        batch_op.drop_column('sprite_img')
        batch_op.drop_column('user_id')
        batch_op.drop_column('base_hp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_hp', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sprite_img', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('base_attack', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('base_defense', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('post_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
