"""empty message

Revision ID: f0e1e09e4a65
Revises: e84adadbacfa
Create Date: 2024-02-25 09:20:58.462207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e1e09e4a65'
down_revision = 'e84adadbacfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_hp', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('base_attack', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('base_defense', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('sprite_img', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('sprite_img')
        batch_op.drop_column('base_defense')
        batch_op.drop_column('base_attack')
        batch_op.drop_column('base_hp')

    # ### end Alembic commands ###
